version: "3.8"

services:
    water_billing_backend:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: water_billing_backend
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - mysql
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: water_billing_nginx
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "9001:80"
        depends_on:
            - water_billing_backend
        networks:
            - app-network

    mysql:
        image: mysql:5.7
        container_name: water_billing_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: water_billing
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: water_billing_phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: water_billing_mysql
            PMA_PORT: 3306
        ports:
            - "8080:80"
        depends_on:
            - mysql
        networks:
            - app-network

volumes:
    db_data:

networks:
    app-network:
        driver: bridge
