version: "3.8"

services:
    # PHP-FPM (Laravel backend)
    water_billing_backend:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: water_billing_backend
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html # Mount Laravel project
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini # (optional php.ini overrides)
        depends_on:
            - mysql
        networks:
            - app-network

    # Nginx web server
    nginx:
        image: nginx:alpine
        container_name: water_billing_nginx
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "9001:80" # Host:Container
        depends_on:
            - water_billing_backend
        networks:
            - app-network

    # MySQL database
    mysql:
        image: mysql:5.7
        container_name: water_billing_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: water_billing
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql # Persist DB data
        networks:
            - app-network

    # PhpMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: water_billing_phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: water_billing_mysql
            PMA_PORT: 3306
        ports:
            - "8080:80"
        depends_on:
            - mysql
        networks:
            - app-network

volumes:
    db_data:

networks:
    app-network:
        driver: bridge
